name : Hello World
on :
    push :
        branches :
            - master
jobs :
  hello :
    runs-on : ubuntu-latest
    steps :
        - name : say hello
          run :  read name ; echo "Hello world from $name"  #comment added